### ISSUE TITLE
possible change sdk version from 10069 to 10586?

### ISSUE THREAD

**Issue by jasonbu** [ciniml/Win10IoTBLEScanner#1]

**Comment by ciniml** [comment]
I've updated target platform to 10586 and checked it runs correctly on my Windows 10 64bit machine.

If you can run UWP apps targeted for 10586, please give it a try on your machine.

**Comment by jasonbu** [comment]
It works perfectly~,  10586 thankyou~ , and Now i'm looking for demo code for gatt ,

https://github.com/ms-iot/samples/tree/develop/BluetoothGATT/CS

this one got some bugs.. It cannot run allright with my device
